---
version: "3"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ./data/calibre/config:/config
      - ./data/media:/media
    ports:
      - 8281:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped



  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./data/calibre/web-config:/config
      - ./data/calibre/config/library:/books
      - ./data/media:/media
    ports:
      - 8083:8083
    restart: unless-stopped



networks: 
  default: 
    external: true
    name: medianetwork
