---


services:
  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    restart: unless-stopped
    privileged: true
    ports:
      - 3001:3001
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_SPEED_TEST_INTERVAL: 480 ## every 8 hours
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_SHOW_HOST: true
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: false
      DASHDOT_ACCEPT_OOKLA_EULA: true

networks:
  default:
    external: true
    name: medianetwork
