

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ./data/homarr/configs:/app/data/configs
      - ./data/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/homarr/data:/data
    ports:
      - "7575:7575"
    environment:
      - DEFAULT_COLOR_SCHEME=dark
      - DISABLE_ANALYTICS=true
      - TZ=Etc/UTC
      - AUTH_PROVIDER=credentials

networks:
  default:
    external: true
    name: medianetwork
