---
services:
  plex:
    image: ghcr.io/hotio/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - PLEX_ADVERTISE_URL=""
      - PLEX_NO_AUTH_NETWORKS=""
      - PLEX_BETA_INSTALL=false
      - PLEX_PURGE_CODECS=false
      - PLEX_CLAIM_TOKEN=claim-ftZxTQSPBMLJf9JMAsCd
    volumes:
      - ./data/plex/test-videos:/test-videos
      - ./data/plex/config:/config
      - ./data/plex/transcode:/transcode
      - /Volumes/wd2:/hdd1
    restart: unless-stopped
    ports:
      - 32400:32400

networks:
  default:
    external: true
    name: medianetwork
