---

# todo setup vpn
# admin-adminadmin
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    ports:
      - "8080:8080"
      # - "8118:8118"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp,8080/udp
      # - VPN_ENABLED=true
      # - VPN_LAN_NETWORK
      # - VPN_CONF=wg0
      # - VPN_ADDITIONAL_PORTS
      # - PRIVOXY_ENABLED=false
    volumes:
      - ./data/qbittorrent/config:/config
      - /Volumes/wd2:/hdd1

    # cap_add:
    #   - NET_ADMIN
    # sysctls:
    #   - net.ipv4.conf.all.src_valid_mark=1
    #   - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped


networks: 
  default: 
    external: true
    name: medianetwork
