---

services:
  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./data/radarr/config:/config
      - ./data/media:/media
      - ./data/media/series:/series
      - ./data/media/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped


networks: 
  default: 
    external: true
    name: medianetwork
