---
version: "3.7"
services:
  sonarr:
    image: cr.hotio.dev/hotio/sonarr:release
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./data/sonarr/config:/config
      - ./data/media:/media
      - ./data/media/series:/series
      - ./data/media/movies:/movies
    ports:
      - 8989:8989
    restart: unless-stopped


networks: 
  default: 
    external: 
      name: medianetwork
