---


services:
  uptime:
    image: louislam/uptime-kuma:latest
    container_name: uptime
    restart: always
    ports:
      - 3002:3001
    volumes:
      - ./data/uptime:/app/data

networks:
  default:
    external: true
    name: medianetwork

  # auth is disabled
