---
version: "3"
services:
  watchtower:
    image: registry.hub.docker.com/containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config-linked.json
    command: --interval 86400
    restart: unless-stopped

networks: 
  default: 
    external: 
      name: medianetwork
