apiVersion: v1
kind: Service
metadata:
  name: {{ include "test1.fullname" . }}
  labels:
    {{- include "test1.labels" . | nindent 4 }}
  annotations:
    portForward: "This service can be port forwarded"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: http
  selector:
    {{- include "test1.selectorLabels" . | nindent 4 }}
  
