apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          env:
            - name: PUID
              value: "501"
            - name: PGID
              value: "20"
          volumeMounts:
            - name: videos
              mountPath: /videos
          ports:
            - containerPort: 32400
            - containerPort: 3005
            - containerPort: 8324
            - containerPort: 32469
            - containerPort: 1900
              protocol: UDP
            - containerPort: 32414
              protocol: UDP
            - containerPort: 32413
              protocol: UDP
            - containerPort: 32412
              protocol: UDP
            - containerPort: 32410
              protocol: UDP
            - containerPort: 5353
              protocol: UDP
      volumes:
        - name: videos
          hostPath:
            path: ~/videos
            type: Directory
