apiVersion: v1
kind: Service
metadata:
  name: plex-test
spec:
  selector:
    app: plex
  ports:
    - name: http
      port: 32400
      targetPort: 32400
    - name: udp
      port: 1900
      targetPort: 1900
      protocol: UDP
    - name: management
      port: 3005
      targetPort: 3005
      protocol: TCP
    - name: mdns
      port: 5353
      targetPort: 5353
      protocol: UDP
    - name: discovery
      port: 8324
      targetPort: 8324
      protocol: TCP
    - name: udp1
      port: 32410
      targetPort: 32410
      protocol: UDP
    - name: udp2
      port: 32412
      targetPort: 32412
      protocol: UDP
    - name: udp3
      port: 32413
      targetPort: 32413
      protocol: UDP
    - name: udp4
      port: 32414
      targetPort: 32414
      protocol: UDP
    - name: http2
      port: 32469
      targetPort: 32469
      protocol: TCP
